apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default-ec2
spec:
  amiFamily: AL2
  role: {{ .Values.roleName }}
  subnetSelectorTerms:
    - tags:
        "kubernetes.io/cluster/{{ .Values.clusterName }}": "shared"
        "kubernetes.io/role/internal-elb": "1"
  securityGroupSelectorTerms:
    - tags:
        "kubernetes.io/cluster/{{ .Values.clusterName }}": "owned"
  tags:
    "karpenter.sh/discovery": "{{ .Values.clusterName }}"
